version: "2"

services:
  web:
    build:
      context: .
    container_name: amazon-scraper-dev
    ports:
      - "8000:80"
    volumes:
      - ./php-code/:/php-code/
      - ./py-code/:/py-code/
      - ./data/:/php-code/data/
    environment:
      - PROD=dev
      - SERVERURL=http://localhost:8000
      - MAIL_USER=example@gmail.com
      - MAIL_PW=password
      - MAIL_RECEIVER=example@mail.com